version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"

  celery_worker:
    build: .
    command: celery -A app.celery.worker:celery worker --loglevel=info
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    depends_on:
      - redis
      - db
  celery_beat:
    build: .
    command: celery -A app.celery.worker:celery beat --loglevel=info
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    depends_on:
      - redis
      - db
volumes:
  postgres_data:
